# Generated by Django 5.0.5 on 2024-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_quarto_foto_quarto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='descricao2',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='descricao3',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='foto_quarto',
            field=models.ImageField(upload_to='foto_quartos/'),
        ),
    ]
