# Generated by Django 5.0.5 on 2024-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_descricao2_hotel_descricao3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='descricao',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='descricao2',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='descricao3',
            field=models.TextField(max_length=1500),
        ),
    ]
